### ISSUE TITLE
Eat out of module hooks

### ISSUE THREAD

**Issue by Ar-King** [stevemk14ebr/PolyHook_2_0#5] opened 2018-10-31 11:57 UTC
EffectTracker eatEffectTracker;

typedef void(__stdcall*tEatTestExport)(int a);
tEatTestExport oEatTestExport;

extern "C" __declspec(dllexport)  int __stdcall  EatTestExport(int a)
{
	return a;
}

int __stdcall hkEatTestExport(int a)
{
	MessageBox(0, "0", "0", 0);
	eatEffectTracker.PeakEffect().trigger();
}

void main()
{
	PLH::EatHook hook("EatTestExport", L"test.exe", (char*)&hkEatTestExport, (uint64_t*)&oEatTestExport);
	hook.hook();

	tEatTestExport pExport = (tEatTestExport)GetProcAddress(GetModuleHandle(nullptr), "EatTestExport");

	eatEffectTracker.PushEffect();
	pExport(1);
	eatEffectTracker.PopEffect().didExecute();
	hook.unHook();
}

**Comment by stevemk14ebr** [comment] 2018-10-31 12:05
please explain the issue you are having in depth

**Comment by Ar-King** [comment] 2018-10-31 12:06
My program can not be executed normally, is it a code problem?

**Comment by stevemk14ebr** [comment] 2018-10-31 12:08
I will try your code when I have free time. 'Normally' doesn't help, what is the error your see, or explain what is unexpected

**Comment by Ar-King** [comment] 2018-10-31 12:08
My hook __stdcall exported function failed。Is this type of hook not supported?

**Comment by Ar-King** [comment] 2018-10-31 12:10
Can you give me an example of eat hook Windows API, such as MessageBox?

**Comment by stevemk14ebr** [comment] 2018-10-31 12:38
definitely a bug here, i'll take a look when i get some time.

**Comment by Ar-King** [comment] 2018-10-31 12:40
You write great code and I love your style. Recently, a project needs to refer to your lib file. I don't know when it will be processed or what I can do to help。

**Comment by stevemk14ebr** [comment] 2018-10-31 14:42
Appreciate the kind words, what do you mean by 

> I don't know when it will be processed or what I can do to help。

I found the bug too. The issue is in how the EAT works, it's AddressOfFunctions array is actually an array of offsets relative to the DLL. This is why it breaks when you do a WinAPI hook, it find the export fine then tries to replace the entry with an offset to the callback by this offset calculation:

`*pExport = (uint32_t)(m_fnCallback - m_moduleBase);`

Unfortunately the m_moduleBase is the base of User32.dll, and not of the exe. This then calculate the wrong offset, and points to some garbage location inside User32.dll once the EAT is traversed again. To fix you'd need to allocate something within User32.dll to transfer control to the exe, it's slightly complicated to do this right (unless i'm missing something).

So congrats you found a flaw, unfortunately I think this is something I won't fix for a while until I get a new implementation idea. I'd a different hooking method if I were you.

This doesn't effect IAT hooks, the IAT is not an offset table but a legit table of pointers.

**Comment by Ar-King** [comment] 2018-11-01 07:38
I can't speak English, maybe there is something wrong with semantic translation. I really appreciate your help.

**Comment by Ochii** [comment] 2018-11-13 17:46
Sorry about that, I overlooked that issue.

@stevemk14ebr we could calculate if we are in front of the target's base address. If we are, good, just calculate the offset and write the result to the EAT entry.
If not, allocate memory after the target's base address (VirtualAlloc?), write a jump to our actual hook function in the allocated memory and point the EAT entry to it.
What do you think?

**Comment by stevemk14ebr** [comment] 2018-11-13 18:46
I've pushed the start of the implementation, it can at least detect this case and fail appropriately now. I'll properly finish it later when i have some time. I'll accept PR's though too 😄

**Comment by Ochii** [comment] 2018-11-14 16:11
Would it be fine to use the existing Detour methods? Or do you prefer that the EAT class does stuff on its own?

**Comment by stevemk14ebr** [comment] 2018-11-14 16:19
I'm considering factoring out the 'makeJmp' methods of the detours into some namespace/object so they can be shared by EAT and Detours. The EAT should be separate from the detours as much as possible and if they share functionality then it should be first broken out into a third place.

**Comment by stevemk14ebr** [comment] 2018-11-14 16:33
The implementation is going to have to control the allocation by manually walking the virtual pages. I tried the following code to brute force the allocation address such that it's <= 32 bits and thus in range and it never broke out:

```
/* We cannot control allocation address here, so try it until we get one within range*/
bool needFree = false; // could use m_trampoline == null, but i like locality (less side-effects)
do {
	// if we are coming back around again, free old attempt
	if (needFree) {
		needFree = false;
		delete[] m_trampoline;
		m_trampoline = nullptr;
	}

	m_trampoline = new uint8_t[32]; 
	needFree = true;
	MemoryProtector prot((uint64_t)m_trampoline, sizeof(uint8_t) * 32, PLH::ProtFlag::R | PLH::ProtFlag::W | PLH::ProtFlag::X, false);
	*m_trampoline = (uint8_t)0xCC;
	offset = (uint64_t)m_trampoline - m_moduleBase;
} while (offset > std::numeric_limits<uint32_t>::max());
```

So we need to instead do something like what i did in V1: https://github.com/stevemk14ebr/PolyHook/blob/master/PolyHook/PolyHook.hpp#L143

**Comment by stevemk14ebr** [comment] 2018-11-15 05:52
Please try master. I've hopefully resolved this: 5cd7d5021e82f3813eb8bad515e68830b5de9621

**Comment by FFFF0h** [comment] 2018-11-15 11:43
Hi,
I had the same issue and now it seems that the problem is solved. BUT, I'm facing a new one: I cannot hook multiple WINAPI. The first hook always work, but the following EAT hooks failed. Maybe, I'm not doing it the right way. Can you help me ?

decltype(GetSystemTime)* Original_GetSystemTime;
void WINAPI Hook_GetSystemTime(PSYSTEMTIME systemTime)
{
	odprintf("[EAT] GetSystemTime called!");
	GetSystemTime(systemTime);
}

decltype(GetLocalTime)* Original_GetLocalTime;
void WINAPI Hook_GetLocalTime(PSYSTEMTIME systemTime)
{
	odprintf("[EAT] GetLocalTime called!");
	GetLocalTime(systemTime);
}

void HookMe()
{
	// GetSystemTime
	PLH::EatHook hook_GST("GetSystemTime", L"kernel32.dll", (char*)&Hook_GetSystemTime, (uint64_t*)&Original_GetSystemTime);
	if (!hook_GST.hook())
	{
		odprintf("[EAT] EAT hooking GetSystemTime failed!");
		return false;
	}

	// GetLocalTime
	PLH::EatHook hook_GLT("GetLocalTime", L"kernel32.dll", (char*)&Hook_GetLocalTime, (uint64_t*)&Original_GetLocalTime);
	if (!hook_GLT.hook())
	{
		odprintf("[EAT] EAT hooking GetLocalTime failed!");
		return false;
	}
}

**Comment by stevemk14ebr** [comment] 2018-11-15 15:22
darn probably not enough free pages to alloc one for each export hooked. Ok so i need to make my page walking smarter and re-use the same page for multiple hook types, give me a day or so.

**Comment by stevemk14ebr** [comment] 2018-11-15 20:08
Update: 350f49601b1eff8442beefab264095fea59c57a2
adds page-reuse across hooks. Current problem is small PAGE_NO_ACCESS region after every module, WIP: https://www.unknowncheats.me/forum/general-programming-and-reversing/307472-alloc-page-walk-issue.html#post2283408

**Comment by stevemk14ebr** [comment] 2018-11-16 00:20
check it now, i think i fixed it

**Comment by FFFF0h** [comment] 2018-11-16 14:29
It works !
thanks

**Closed** 2018-11-16 14:39 UTC
